apiVersion: v1
kind: Secret
metadata:
  name: pandawa-secret
type: Opaque
stringData:
  NEXTAUTH_SECRET: "LMvrmo42yk1qmjCSiN6VuLmYETvog/d1oEWzehA4W+c="
  DATABASE_URL: "postgres://postgres:supersecretpassword@cakradigital.my.id:5432/pandawa?schema=public"