-- AlterTable
ALTER TABLE "prediksi_panen" ALTER COLUMN "luas_panen" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hasil_prediksi" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hasil_rata_rata" SET DATA TYPE DOUBLE PRECISION;
